### ISSUE TITLE
Retos Python Study Group 

### ISSUE THREAD

**Issue by jevillanueva** [ValentinEspinoza/psg-example#3]
Hola!

Me gustaria invitarte a que continues 😄 
Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/
No te desanimes!! estare atento a tus retos, animo!!! 

--- 
Feedback:
5.3. Esta bien pero tiene bugs, puedes usar las divisiones enteras la salida es simiar a: 3 dias, 8 horas, 5 minutos y 25 segundos.
Ya salieron los retos de la sesión 11!!!

Estas haciendo un gran gran trabajo! felicidades es genial leer tu codigo
Estare por aqui dandome vueltas en los repos, si tienes algunda duda o consulta no dudes en responder a este issue o tambien por el grupo de whatsapp

Sigue adelante!! Gran trabajo!!  

> El código limpio siempre parece que fue escrito por alguien que se preocupaba. - Michael Feathers

**Comment by ValentinEspinoza** [comment]
De acuerdo, revise y modifique la resolución del ejercicio_03.

Muchas gracias por la retroalimentación y los ánimos 😁 👍👍
